name: Bug Report
description: Report a bug in this TypeScript template
labels: [bug]

body:
  - type: dropdown
    id: affected-area
    attributes:
      label: Which area is impacted by the bug?
      options:
        - build
        - testing
        - linting
        - packages
        - configuration
        - pipeline
        - documentation
        - don't know/not listed
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Anything else?
